[DATA]
data_set = 'https://raw.githubusercontent.com/5x12/ml-cookbook/master/supplements/data/heart.csv'

[MODEL_KNC]
dt_conf = "model/conf/KNeighborsClassifier.pkl"

[MODEL_KNR]
dt_conf = "model/conf/KNeighborsRegressor.pkl"